import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";


const font = Poppins({   weight: ['200', '300' , '400', '500',  '700', '900'],
style: ['normal', 'italic'],
subsets: ['latin'],
display: 'swap' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} flex  grow flex-col items-center md:px-24` }>{children}</body>
    </html>
  );
}
